/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.amf.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AMFTrackEventEntry service. Represents a row in the &quot;AMFTrackEventEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.amf.model.impl.AMFTrackEventEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.amf.model.impl.AMFTrackEventEntryImpl}.
 * </p>
 *
 * @author Calvin Keum
 * @see AMFTrackEventEntry
 * @see com.liferay.amf.model.impl.AMFTrackEventEntryImpl
 * @see com.liferay.amf.model.impl.AMFTrackEventEntryModelImpl
 * @generated
 */
@ProviderType
public interface AMFTrackEventEntryModel extends BaseModel<AMFTrackEventEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a amf track event entry model instance should use the {@link AMFTrackEventEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this amf track event entry.
	 *
	 * @return the primary key of this amf track event entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this amf track event entry.
	 *
	 * @param primaryKey the primary key of this amf track event entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the amf track event entry ID of this amf track event entry.
	 *
	 * @return the amf track event entry ID of this amf track event entry
	 */
	public long getAmfTrackEventEntryId();

	/**
	 * Sets the amf track event entry ID of this amf track event entry.
	 *
	 * @param amfTrackEventEntryId the amf track event entry ID of this amf track event entry
	 */
	public void setAmfTrackEventEntryId(long amfTrackEventEntryId);

	/**
	 * Returns the create date of this amf track event entry.
	 *
	 * @return the create date of this amf track event entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this amf track event entry.
	 *
	 * @param createDate the create date of this amf track event entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the user ID of this amf track event entry.
	 *
	 * @return the user ID of this amf track event entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this amf track event entry.
	 *
	 * @param userId the user ID of this amf track event entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this amf track event entry.
	 *
	 * @return the user uuid of this amf track event entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this amf track event entry.
	 *
	 * @param userUuid the user uuid of this amf track event entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the type of this amf track event entry.
	 *
	 * @return the type of this amf track event entry
	 */
	public int getType();

	/**
	 * Sets the type of this amf track event entry.
	 *
	 * @param type the type of this amf track event entry
	 */
	public void setType(int type);

	/**
	 * Returns the ip address of this amf track event entry.
	 *
	 * @return the ip address of this amf track event entry
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this amf track event entry.
	 *
	 * @param ipAddress the ip address of this amf track event entry
	 */
	public void setIpAddress(String ipAddress);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AMFTrackEventEntry amfTrackEventEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AMFTrackEventEntry> toCacheModel();

	@Override
	public AMFTrackEventEntry toEscapedModel();

	@Override
	public AMFTrackEventEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}